
exports.seed = function(knex, Promise) {
  return knex('inventory')
    .del()
    .then(() => {
      return knex('inventory').insert([
        {id: 1, item: 'Fodera Emperor Standard', price: 5850.00, item_description: "Ask any serious bass player, and they'll tell you that Fodera is among the best of the best bass makers in the world, and you can see that reputation reflected in their Emperor 5 Standard model. This premium 5-string bass was handcrafted by the same luthiers in the same shop responsible for creating Fodera's world-class custom instruments, and the materials used are second to none. The 5A flame maple top on the medium-weight ash body is breathtaking to behold, while an old-growth pau ferro fingerboard on a quartersawn rock maple neck plays like a fine-tuned Formula 1 racer. Top it off with Fodera dual-coil pickups, and you can't go wrong with an Emperor 5 Standard.", item_url: "https://cdn3.volusion.com/nvcpd.gmazx/v/vspfiles/photos/FoderaMonarch5BOBuckeye5799-2T.jpg?1446651323"},
        {id: 2, item: 'Yamaha John Patitucci 6-string Signature Bass', price: 2899.99, item_description: "The Yamaha TRBJP2 6-string solidbody electric bass guitar was created by a meeting of the minds with one of the most respected bass players of our time, John Patitucci. A decades long career, playing in some of the most coveted bass gigs on earth, Mr. Patitucci knows what he, and you would want in a bass. So Yamaha let John specify everything he needed on the TRBJP2. From body construction, to pickup design, and the EQ frequencies of the active preamp. Sweetwater knows that you're getting a professional quality bass with the Yamaha TRBJP2.", item_url: "http://store.basscentral.com/content/assets/41/411356/Yamaha_Bass/YAMAHAPATITUCCI6AMBER074EFRT.jpg"},
        {id: 3, item: 'Ernie Ball Music Man Bongo 6 HH', price: 2249.00, item_description: "The Ernie Ball Music Man Bongo 6 HH is a beautifully balanced 6-string electric bass with a resonant basswood body, fast-playing maple neck, and a rosewood fingerboard. The Bongo bass has been embraced by top bassists, such as John Myung and Dave LaRue, and it's easy to see why. A generous double cutaway design gives you effortless access to the upper register, while two powerful humbuckers with neodymium magnets deliver boatloads of beefy tone. An onboard 18-volt preamp with a 4-band EQ completes the Ernie Ball Music Man Bongo 6 HH, delivering an extremely wide array of tones.", item_url: "http://d2ydh70d4b5xgv.cloudfront.net/images/3/d/ernie-ball-music-man-musicman-bongo-6-string-bass-stealth-black-ce53bfc52e940b1b3081df765b3d6366.jpg"},
        {id: 4, item: 'Ibanez BTB746 BTB Standard', price: 949.99, item_description: "The 5-piece maple and rosewood neck is flanked by mahogany and ash wings topped with walnut. This unique tonewood combination serves as a recipe for complex harmonics and epic sustain. Making the most of this foundation is a set of Bartolini BH2 humbucking pickups accompanied by a flexible 3-band active EQ. Finally, professional touches such as a 6-piece Mono-rail V bridge, a zero-fret nut, and even a locking output jack provide the Ibanez BTB746 with all the hallmarks of an instrument you'll never let go.", item_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTJLDmHe65hCryo9bJ10HpX82nTwj3dwb02dPc9QF3u4BwjA6hm4g"},
        {id: 5, item: 'Ibanez Bass Workshop SRFF806BKS Multi-Scale', price: 1049.99, item_description: "The Ibanez SRFF806BKS 6-string bass rocks an ash body, a 5-piece jatoba/bubinga neck, and 24 multi-scale frets on its rosewood fingerboard. Multi-scale frets yield a longer scale on the bass side of the instrument and a shorter scale on the treble side. This gives you better intonation and more consistent tension and attack from string to string. The SRFF806BKS is fitted with two Bartolini BH1 pickups that deliver a mountain of tone. Many Sweetwater bassists are into multi-scale frets. You can be, too, with the Ibanez SRFF806BKS.", item_url: "http://ergnerds.com/wp-content/uploads/2015/03/SRFF.jpg"},
      ]);
    });
};
